<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
<div class="note-msg"> <?php echo $this->__('There are no products matching the selection. Please provide a category ID.') ?> </div>
<?php else: ?>
<?php // Grid Mode ?>
<ul id="second-carousel" class="first-and-second-carousel jcarousel-skin-ie7">
  <?php $_collectionSize = $_productCollection->count() ?>
  <?php $i=0; foreach ($_productCollection as $_product): ?>
  <?php if($i++%4==0): ?>
  <?php endif ?>
  <li> <a class="preview" rel="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300, 300); ?>" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"> <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(140, 140); ?>" width="140" height="140" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /> </a>
    <p class="carousel-title"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></p>
    <?php echo $this->getPriceHtml($_product, true) ?> </li>
  <?php if ($i%4==0 && $i!=$_collectionSize): ?>
  <?php endif ?>
  <?php endforeach ?>
</ul>
<?php endif; ?>
